hardware_columns:
  TX2:
  - core_freq
  - gpu_freq
  - emc_freq
  - num_cores
software_columns:
  Image:
  - memory_growth
  - logical_devices
kernel_columns:
- scheduler_policy
- vm_swappiness 
- vm_vfs_cache_pressure
- vm_dirty_background_ratio
- vm_drop_caches
- vm_nr_hugepages
- vm_overcommit_ratio
- vm_overcommit_memory
- vm_overcommit_hugepages
- kernel_sched_child_runs_first
- kernel_sched_rt_runtime_us
- vm_dirty_bytes
- vm_dirty_background_bytes
- vm_dirty_ratio
- swap_memory
- kernel_max_pids
- kernel_sched_latency_ns
- kernel_sched_nr_migrate
- kernel_cpu_time_max_percent
- kernel_sched_time_avg_ms
option_values:
    TX2:
        core_freq:
        - 345600 
        - 499200
        - 652800 
        - 806400 
        - 960000
        - 1113600
        - 1267200
        - 1420800
        - 1574400
        - 1728000
        - 1881600
        - 2035200
        
        gpu_freq:
        - 140250000
        - 229500000
        - 318750000
        - 408000000
        - 497250000
        - 675750000
        - 765000000
        - 854250000
        - 1032750000
        - 1122000000
        - 1211250000
        - 1300500000
        emc_freq:
        - 40800000
        - 68000000
        - 102000000
        - 204000000
        - 665600000
        - 1062400000
        - 1331200000
        - 1866000000
        num_cores:
        - 1 
        - 2
        - 3
        - 4 
        scheduler_policy:
        - 0 
        - 1
        logical_devices:
        - 0
        - 1 
        vm_swappiness:
        - 10
        - 60
        - 100  
        vm_vfs_cache_pressure:
        - 0
        - 100
        - 500  
        vm_dirty_background_ratio:
        - 10
        - 80 
        vm_drop_caches:
        - 0
        - 1
        - 2
        - 3 
        kernel_sched_child_runs_first:
        - 0
        - 1 
        kernel_sched_rt_runtime_us: 
        - 500000
        - 950000
        vm_dirty_bytes:
        - 30
        - 60
        vm_dirty_background_bytes:
        - 30
        - 60
        vm_dirty_ratio:
        - 5
        - 50
        vm_overcommit_ratio:
        - 50
        - 80
        vm_overcommit_memory:
        - 0
        - 2
        kernel_cpu_time_max_percent:
        - 10
        - 100
        kernel_sched_time_avg_ms:
        - 1000
        - 2000
        kernel_sched_rt_period_us: 
        - 1000000
        - 2000000
        kernel_sched_nr_migrate:
        - 32
        - 64
        - 128
        vm_overcommit_hugepages:
        - 0
        - 1
        - 2
        memory_growth:
        - 0.5
        - 0.9 
        vm_nr_hugepages:
        - 1
        - 2
        presets:
        - 0
        - 1
        - 2
        maximum_rate:
        - 600000
        - 1000000
        
        swap_memory:
        - 2
        - 4
        kernel_max_pids:
        - 32768
        - 65536
        kernel_sched_latency_ns:
        - 24000000
        - 96000000
util_dir: "utils"
output_dir: "data/output"
config_file: params.py
init_dir: "data/initial"
bug_dir: "data/bug"
opt_dir: "data/measurement/optimization"
debug_dir: "data/measurement/debug"
sampled_dir: "data/sampled"

